
services:
  app1:
    build: .
    container_name: amm_volume_bot_1
    env_file:
      - .env
      - env.instance1
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

